# frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: project 
spec:
  selector:
    app: frontend-app
  ports:
  - port: 8080
    targetPort: 8080 

--- 

# service for backend 

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project 
spec:
  selector:
    app: backend-app
  ports:
  - port: 5000
    targetPort: 5000

